#!/bin/sh

if [ -z "$VPN_NAME" ]; then
	echo "ERROR: no vpn name has been set" >&2
	exit 1
fi

if ! [ -d "/etc/tinc/$VPN_NAME" ]; then
	echo "ERROR: missing vpn configuration directory" >&2
	exit 1
fi

if [ -z "$VPN_NODE" ]; then
	echo "ERROR: no vpn nodename assigned" >&2
	exit 1
fi

if [ -z "$VPN_ADDR" ]; then
	echo "ERROR: no vpn address assigned" >&2
	exit 1
fi

export VPN_NAME VPN_ADDR VPN_NODE
exec tincd "$@" -n $VPN_NAME -o Name=$VPN_NODE
