#!/bin/sh

log_and_exec() {
	echo '* ' "$@"
	"$@"
}

if ! iptables -t nat -C POSTROUTING -o eth0 -j MASQUERADE > /dev/null 2>&1; then
	log_and_exec iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
fi
