#!/bin/sh

ROUTES="/etc/tinc/$VPN_NAME/routes"
TINC_UP_LOCAL="/etc/tinc/$VPN_NAME/tinc-up-local"

ip addr add $VPN_ADDR dev $INTERFACE
ip link set $INTERFACE up

if [ -x "$TINC_UP_LOCAL" ]; then
	$TINC_UP_LOCAL
fi
