#!/bin/sh

ip_exists() {
	local addrs
	local addr

	ip addr | awk '$1 == "inet" {print $2}' | cut -f1 -d/ |
		grep '^'"$1"'$'
}

mkdir -p /run/dnsmasq/servers.conf.d

incrond

if [ "$DNSMASQ_LISTEN_ADDR" ]; then
	DNSMASQ_LISTEN_OPTION="--listen-address $DNSMASQ_LISTEN_ADDR"

	echo "waiting for address $DNSMASQ_LISTEN_ADDR"
	while ! ip_exists $DNSMASQ_LISTEN_ADDR; do
		sleep 1
	done
fi

exec dnsmasq -k \
	--user=root \
	--conf-file=/dev/null \
	--conf-dir='/etc/dnsmasq.d,*.conf' \
	--servers-file=/run/dnsmasq/servers.conf \
	$DNSMASQ_LISTEN_OPTION \
	"$@"
